global:
  namespace: host
  tag: v1.0.0
  githubRepo: MidasWR/ShareMTC

postgres:
  host: host-db
  port: "5432"
  database: host
  sslmode: require
  userSecretName: host.host-db.credentials.postgresql.acid.zalan.do
  usernameKey: username
  passwordKey: password

auth:
  dns: authservice
  image: midaswr/host-authservice
  port: 8081

admin:
  dns: adminservice
  image: midaswr/host-adminservice
  port: 8082
  agentInstaller:
    resourceApiURL: http://167.71.47.177
    kafkaBrokers: 167.71.47.177:9092
    imageRepo: midaswr/host-hostagent

resource:
  dns: resourceservice
  image: midaswr/host-resourceservice
  port: 8083
  provisioningBaseURL: http://provisioningservice:8085
  createRateLimitRPM: 5
  vmTTLMinutes: 5

provisioning:
  dns: provisioningservice
  image: midaswr/host-provisioningservice
  port: 8085
  ttlWorkerIntervalSeconds: 15
  providerSecretName: host-provider-secrets
  digitalOceanTokenKey: dop_v1_6a76fd43122df82316c35fe732908ffdebb28167638d4f2f79f669db042897f1
  runpodApiKeyKey: RUNPOD_API_KEY

security:
  serviceSecretName: host-service-secrets
  provisioningServiceTokenKey: PROVISIONING_SERVICE_TOKEN

billing:
  dns: billingservice
  image: midaswr/host-billingservice
  port: 8084

frontend:
  dns: frontend-service
  image: midaswr/host-frontend
  port: 80

hostagent:
  enabled: false
  dns: hostagent
  image: midaswr/host-hostagent

kafka:
  bootstrapService: host-kafka-kafka-bootstrap
