apiVersion: v1
kind: ConfigMap
metadata:
  name: host-services-config
  namespace: {{ .Values.global.namespace }}
data:
  REDIS_ADDR: "redis.{{ .Values.global.namespace }}.svc.cluster.local:6379"
  KAFKA_BROKERS: "{{ .Values.kafka.bootstrapService }}.{{ .Values.global.namespace }}.svc.cluster.local:9092"
