global:
  namespace: host

kafka:
  clusterName: host-kafka
  version: 3.9.0
  replicas: 1
  topicMetrics: host.metrics
  topicHealth: host.health
  vpa:
    enabled: false
    namespace: host

redis:
  dns: redis

envoy:
  dns: envoy-gateway

prometheus:
  dns: prometheus

postgres:
  dns: host-db

falco:
  enabled: false
  dns: falco
  image: public.ecr.aws/falcosecurity/falco
  tag: 0.38.2

kyverno:
  dns: kyverno

spark:
  enabled: false
  dns: spark
  image: apache/spark
  tag: 3.5.8-scala2.12-java17-python3-ubuntu

atlas:
  dns: atlas
  migration:
    enabled: false
    urlSecretName: atlas-db-url
    urlSecretKey: url
    remoteDirName: ""
    remoteDirTag: latest
