global:
  namespace: host

kafka:
  clusterName: host-kafka
  version: 3.9.0
  replicas: 1
  topicMetrics: host.metrics
  topicHealth: host.health
  vpa:
    enabled: false
    namespace: host

redis:
  dns: redis

envoy:
  dns: envoy-gateway

prometheus:
  dns: prometheus

postgres:
  dns: host-db

falco:
  dns: falco

kyverno:
  dns: kyverno

spark:
  dns: spark

atlas:
  dns: atlas
  migration:
    enabled: false
    urlSecretName: atlas-db-url
    urlSecretKey: url
    remoteDirName: ""
    remoteDirTag: latest
