global:
  namespace: host

kafka:
  clusterName: host-kafka
  version: 3.9.0
  replicas: 1
  topicMetrics: host.metrics
  topicHealth: host.health
  vpa:
    enabled: false
    namespace: host

redis:
  dns: redis

envoy:
  dns: envoy-gateway
  gatewayClassName: envoy

services:
  namespace: host
  auth:
    name: authservice
    port: 8081
  admin:
    name: adminservice
    port: 8082
  resource:
    name: resourceservice
    port: 8083
  billing:
    name: billingservice
    port: 8084
  frontend:
    name: frontend-service
    port: 80

prometheus:
  dns: prometheus

postgres:
  dns: host-db

falco:
  enabled: false
  dns: falco
  image: public.ecr.aws/falcosecurity/falco
  tag: 0.38.2

kyverno:
  dns: kyverno

spark:
  enabled: false
  dns: spark
  image: apache/spark
  tag: 3.5.8-scala2.12-java17-python3-ubuntu

atlas:
  dns: atlas
  migration:
    enabled: true
    urlSecretName: atlas-db-url
    urlSecretKey: url
    remoteDirName: migrations/resourceservice
    remoteDirTag: latest
