apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.dns }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.dns }}
    spec:
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.redis.dns }}
  ports:
    - port: 6379
      targetPort: 6379
