apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kafka-vpa
  namespace: {{ .Values.global.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.kafka.dns }}
  updatePolicy:
    updateMode: Auto
