{{- if .Values.kafka.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kafka-vpa
  namespace: {{ .Values.kafka.vpa.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strimzi-cluster-operator
  updatePolicy:
    updateMode: Auto
{{- end }}
