apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: host-db
  namespace: {{ .Values.global.namespace }}
spec:
  teamId: host
  volume:
    size: 10Gi
  numberOfInstances: 1
  users:
    host:
      - superuser
      - createdb
  databases:
    host: host
  postgresql:
    version: "16"
