apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.provisioning.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.provisioning.dns }}
  template:
    metadata:
      labels:
        app: {{ .Values.provisioning.dns }}
    spec:
      containers:
        - name: {{ .Values.provisioning.dns }}
          image: {{ .Values.provisioning.image }}:{{ default .Chart.AppVersion .Values.global.tag }}
          ports:
            - containerPort: {{ .Values.provisioning.port }}
          env:
            - name: PGHOST
              value: "{{ .Values.postgres.host }}.{{ .Values.global.namespace }}.svc.cluster.local"
            - name: PGPORT
              value: {{ .Values.postgres.port | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: PGSSLMODE
              value: {{ .Values.postgres.sslmode | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.userSecretName }}
                  key: {{ .Values.postgres.usernameKey }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.userSecretName }}
                  key: {{ .Values.postgres.passwordKey }}
            - name: PROVISIONING_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.security.serviceSecretName }}
                  key: {{ .Values.security.provisioningServiceTokenKey }}
            - name: DIGITALOCEAN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.provisioning.providerSecretName }}
                  key: {{ .Values.provisioning.digitalOceanTokenKey }}
            - name: RUNPOD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.provisioning.providerSecretName }}
                  key: {{ .Values.provisioning.runpodApiKeyKey }}
            - name: TTL_WORKER_INTERVAL_SECONDS
              value: {{ .Values.provisioning.ttlWorkerIntervalSeconds | quote }}
          envFrom:
            - configMapRef:
                name: host-services-config
