apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.provisioning.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.provisioning.dns }}
  ports:
    - port: {{ .Values.provisioning.port }}
      targetPort: {{ .Values.provisioning.port }}
