apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.envoy.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  gatewayClassName: {{ .Values.envoy.gatewayClassName | quote }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.envoy.dns }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/auth
      backendRefs:
        - name: {{ .Values.services.auth.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.auth.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /v1/admin
      backendRefs:
        - name: {{ .Values.services.admin.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.admin.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /v1/catalog
      backendRefs:
        - name: {{ .Values.services.admin.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.admin.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /v1/resources
      backendRefs:
        - name: {{ .Values.services.resource.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.resource.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /v1/billing
      backendRefs:
        - name: {{ .Values.services.billing.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.billing.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.envoy.dns }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.services.frontend.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.frontend.port }}
