apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: health-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.envoy.dns }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /healthz/auth
      backendRefs:
        - name: {{ .Values.services.auth.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.auth.port }}
    - matches:
        - path:
            type: Exact
            value: /healthz/admin
      backendRefs:
        - name: {{ .Values.services.admin.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.admin.port }}
    - matches:
        - path:
            type: Exact
            value: /healthz/resources
      backendRefs:
        - name: {{ .Values.services.resource.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.resource.port }}
    - matches:
        - path:
            type: Exact
            value: /healthz/billing
      backendRefs:
        - name: {{ .Values.services.billing.name }}
          namespace: {{ .Values.services.namespace }}
          port: {{ .Values.services.billing.port }}
