apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: health-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.envoy.dns }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /healthz/auth
      backendRefs:
        - name: authservice
          port: 8081
    - matches:
        - path:
            type: Exact
            value: /healthz/admin
      backendRefs:
        - name: adminservice
          port: 8082
    - matches:
        - path:
            type: Exact
            value: /healthz/resources
      backendRefs:
        - name: resourceservice
          port: 8083
    - matches:
        - path:
            type: Exact
            value: /healthz/billing
      backendRefs:
        - name: billingservice
          port: 8084
