apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostagent.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.hostagent.dns }}
  ports:
    - port: 9100
      targetPort: 9100
