apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.hostagent.dns }}-vpa
  namespace: {{ .Values.global.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: {{ .Values.hostagent.dns }}
  updatePolicy:
    updateMode: Auto
