apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.resource.dns }}-vpa
  namespace: {{ .Values.global.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.resource.dns }}
  updatePolicy:
    updateMode: Auto
