apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.dns }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.auth.dns }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.dns }}
    spec:
      containers:
        - name: {{ .Values.auth.dns }}
          image: {{ .Values.auth.image }}:{{ default .Chart.AppVersion .Values.global.tag }}
          ports:
            - containerPort: {{ .Values.auth.port }}
          env:
            - name: PGHOST
              value: "{{ .Values.postgres.host }}.{{ .Values.global.namespace }}.svc.cluster.local"
            - name: PGPORT
              value: {{ .Values.postgres.port | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: PGSSLMODE
              value: {{ .Values.postgres.sslmode | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.userSecretName }}
                  key: {{ .Values.postgres.usernameKey }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.userSecretName }}
                  key: {{ .Values.postgres.passwordKey }}
          envFrom:
            - configMapRef:
                name: host-services-config
